name: Build Chrome Extension

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'manifest.json'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Create .zip
        run: |
          zip -r filtered-chrome.zip . -x "*.git*" "*.github*" "README.md" "LICENSE"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: filtered-chrome
          path: filtered-chrome.zip