name: Release

on:
  push:
    branches: [ main ]
    paths:
      - 'manifest.json'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 2 

      - name: Check if version changed
        id: version_check
        run: |
          OLD_VERSION=$(git show HEAD^:manifest.json | jq -r .version)
          NEW_VERSION=$(jq -r .version manifest.json)
          
          if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "version=v$NEW_VERSION" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create .zip
        if: steps.version_check.outputs.changed == 'true'
        run: |
          zip -r filtered.zip . -x "*.git*" "*.github*" "README.md" "LICENSE"

      - name: Create GitHub Release
        if: steps.version_check.outputs.changed == 'true'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.version_check.outputs.version }}
          name: Release ${{ steps.version_check.outputs.version }}
          files: filtered.zip
          generate_release_notes: true